### ISSUE TITLE
Translate "uncased" keys in response bodies to snake case

### ISSUE THREAD

**Issue by gsterndale** [tweag/stacker_bee#13]
This should probably be a configuration option.

**Comment by nicholaides** [comment]
I can think of 2 approaches for this:
1. Simply convert all keys to snake case. For example, if you were to print out a response, you would see: `disk_bytes_read_rate` instead of `diskBytesReadRate` and `cloud_identifier` instead of `cloudidentifer`. This would be the ideal, in my mind. 

The challenge is that there are ~475 keys that we would need to get right (https://gist.github.com/nicholaides/7185973). It doesn't seem feasible or robust to maintain a list of translations or even a list of rules that would help us translate.
1. Another option would be to make the response objects have "indifferent access", as we did with requests. For example, if you try to access the key `disk_bytets_read_rate` or `diskbytesreadrate`, it would give you the key `diskBytesReadRate`.

Given the challenging nature of option 1, I think option 2 is best.
